services:
  # ----------------------------
  # 1. DATABASE (Postgres)
  # ----------------------------
  postgres:
    image: postgres:15
    container_name: socialgym-db
    environment:
      POSTGRES_USER: socialgym
      POSTGRES_PASSWORD: password
      POSTGRES_DB: socialgym_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ----------------------------
  # 2. KAFKA (Event Bus)
  # ----------------------------
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: socialgym-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093
      # Note: We advertise "kafka" to internal docker containers, and "localhost" to your machine
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # ----------------------------
  # 3. BACKEND (Spring Boot)
  # ----------------------------
  backend:
    build: ./backend
    container_name: socialgym-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - kafka
    environment:
      # OVERRIDE Localhost with Service Names
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/socialgym_db
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      # Pass your API Key (It will read from your .env file or system env)
      OPENAI_API_KEY: ${OPENAI_API_KEY}

  # ----------------------------
  # 4. FRONTEND (React + Nginx)
  # ----------------------------
  frontend:
    build: ./frontend
    container_name: socialgym-frontend
    ports:
      - "80:80" # Opens on port 80 (standard web)
    depends_on:
      - backend

  ml-service:
    build: ./ml-service
    depends_on:
      - kafka
      - postgres
    environment:
      # OVERRIDE Localhost with Service Names
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DB_HOST: postgres

volumes:
  postgres_data: